[package]
name = "superdev"
version = "0.1.0"
edition = "2024"

[dependencies]
anywho = "0.1.2"
axum = "0.8.4"
dotenv = "0.15.0"
envy = "0.4.2"
serde = "1.0.219"
serde_json = "1.0.140"
solana-client = "2.3.2"
solana-sdk = "2.3.1"
tokio = "1.45.1"
